language: node_js
node_js:
  - "4"
  - "5"
matrix:
  allow_failures:
    - node_js: "5"
  fast_finish: true
script: "npm run-script test-travis"
after_script: "test $TRAVIS_NODE_VERSION = '0.10' && npm install coveralls@2.11.1 && cat ./coverage/lcov.info | coveralls"
